name: set-env
author: SangBeom-Hahn
description: 'test'
inputs:
  REF_TYPE:
    description: 'test'
    required: true
    default: 'branch'
  BASE_REF:
    description: 'test'
    required: true
    default: 'dev'
outputs:
  environment:
    description: 'set env'
    value: ${{ steps.set-env.outputs.environment }}

runs:
  using: "composite"
  steps:
  - name: set env
    id: set-env
    shell: bash
    run: |
      if [[ ${{ inputs.REF_TYPE }} == "tag" ]]; then
        echo "environment=qa" >> $GITHUB_OUTPUT
        exit 0
      fi

      if [[ ${{ inputs.REF_TYPE }} == "branch" ]]; then
        echo "environment=dev" >> $GITHUB_OUTPUT

        if [[ ${{ inputs.BASE_REF }} == "master" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT 
        fi
      fi
  - name: check env
    shell: bash
    run: echo ${{ steps.set-env.outputs.environment }}